/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wws;

import java.util.ArrayList;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author bfw
 */
public class BenutzerVerbindungen extends javax.swing.JFrame {

    /**
     * Creates new form BenVerVerwaltung
     */
    public BenutzerVerbindungen() {
        initComponents();
        Show_Verbindungen_In_JTable();
    }

       private void Show_Verbindungen_In_JTable()
    {
//        ArrayList<ObjPcbestand> BestandList = getPCBestand();
        ArrayList<ObjVerbindung> VerbindungenListe = VerbindungXML.getVerbindungenliste();
        DefaultTableModel model = (DefaultTableModel)jTableVerbindungen.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        String regex1 = "^([a-z]{4,5}:)+//"; 
        String regex2 = "/Projekt_WWS$";
//        String regex = "jdbc:mysql:";

        Pattern p1 = Pattern.compile(regex1);
        Pattern p2 = Pattern.compile(regex2);
        
        
        for(int i = 0; i < VerbindungenListe.size(); i++)
        {
            row[0] = VerbindungenListe.get(i).getName();
            Matcher m = p1.matcher(VerbindungenListe.get(i).getUrl());    
            //      entfernt auch /Projekt_WWS:
            //           m = p2.matcher(m.replaceFirst(""));
            row[1] = m.replaceFirst("");
            row[2] = VerbindungenListe.get(i).getBenutzer();
            row[3] = VerbindungenListe.get(i).getPasswort();
            row[4] = VerbindungenListe.get(i).getAktiv();
            
            model.addRow(row);
        }
    }     
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVerbindungen = new javax.swing.JTable();
        jButtonDBHinzufuegen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonDBLoeschen = new javax.swing.JButton();
        jButtonAktiv = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menue.setText("Menue");
        menue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueActionPerformed(evt);
            }
        });

        jTableVerbindungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "URL", "Benutzer", "Passwort", "aktiv"
            }
        ));
        jScrollPane1.setViewportView(jTableVerbindungen);

        jButtonDBHinzufuegen.setText("Hinzufügen");
        jButtonDBHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDBHinzufuegenActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("DB Verbindungen");

        jButtonDBLoeschen.setText("Löschen");
        jButtonDBLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDBLoeschenActionPerformed(evt);
            }
        });

        jButtonAktiv.setText("Aktiv setzen");
        jButtonAktiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAktivActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(menue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDBHinzufuegen)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonDBLoeschen)
                                .addGap(52, 52, 52)
                                .addComponent(jButtonAktiv))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDBHinzufuegen)
                    .addComponent(jButtonDBLoeschen)
                    .addComponent(jButtonAktiv))
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226)
                .addComponent(menue)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menue mm = new menue();
        mm.setVisible(true);
    }//GEN-LAST:event_menueActionPerformed

    private void jButtonDBHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDBHinzufuegenActionPerformed
        // TODO add your handling code here:
        NeueVerbindungJDialog nn = new NeueVerbindungJDialog(this,true);
        nn.setVisible(true);
    }//GEN-LAST:event_jButtonDBHinzufuegenActionPerformed

    private void jButtonDBLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDBLoeschenActionPerformed
        // TODO add your handling code here:

                
        int i = jTableVerbindungen.getSelectedRow();
        TableModel tm = jTableVerbindungen.getModel();
//        System.out.println(tm.getValueAt(i, 0));
        
        if (tm.getValueAt(i,4).toString().equals("true")) {
            Object[] options = {"Ja","Nein"};
            int n = JOptionPane.showOptionDialog(null, "aktive db löschen?","db",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
            
            System.out.println("no "+n);
            if(n==0) {
                boolean ok = VerbindungXML.deleteVerbindung(tm.getValueAt(i,0).toString());
                if (ok) {Show_Verbindungen_In_JTable();}
            }
            
        }  else {        
            boolean ok = VerbindungXML.deleteVerbindung(tm.getValueAt(i,0).toString());
            if (ok) {Show_Verbindungen_In_JTable();}
        }
    }//GEN-LAST:event_jButtonDBLoeschenActionPerformed

    private void jButtonAktivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAktivActionPerformed
        // TODO add your handling code here:
        int i = jTableVerbindungen.getSelectedRow();
        TableModel tm = jTableVerbindungen.getModel();
        boolean ok = VerbindungXML.setVerbindungAktiv(tm.getValueAt(i,0).toString());
        if (ok) {Show_Verbindungen_In_JTable();}
    }//GEN-LAST:event_jButtonAktivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenutzerVerbindungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenutzerVerbindungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenutzerVerbindungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenutzerVerbindungen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenutzerVerbindungen().setVisible(true);
            }
        });
    }

    /*hallo*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAktiv;
    private javax.swing.JButton jButtonDBHinzufuegen;
    private javax.swing.JButton jButtonDBLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVerbindungen;
    private javax.swing.JButton menue;
    // End of variables declaration//GEN-END:variables
}
