/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wws;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bfw
 */
public class BuchungRechner extends javax.swing.JFrame {

    /**
     * Creates new form BuchungRechner
     */
    
    private static int aktuellPCKlasse;
    private static ArrayList<Integer> PCKlassenIDsListe = new ArrayList<>();
    
    
    public BuchungRechner() {
        initComponents();
        fillComboBoxItems();
    }

    
    
    private void fillComboBoxItems() {
        
        ArrayList<pcklasse> pcListe = getPcList();
        int anzahl = pcListe.size();

        String[] itemListe = new String[anzahl];
//        System.out.println(anzahl);
        for (int i = 0; i < anzahl; i++) {
            itemListe[i] = pcListe.get(i).getHersteller() + pcListe.get(i).getModell();
            PCKlassenIDsListe.add(pcListe.get(i).getID());
           
                   
        }        
        PCKlappliste.setModel(new javax.swing.DefaultComboBoxModel<>(itemListe));
    }
    
    private ArrayList<pcklasse> getPcList()
    {
        ArrayList<pcklasse> pcList = new ArrayList<pcklasse>();
    //    Connection connection = getConnection();
        Connection connection = DBConnection.getConnection2();
        
        
        String query = "SELECT * FROM `PCKlasse` ";
        Statement st;
        ResultSet rs;
        
        try
        {
            st = connection.createStatement();
            //rs = st.executeQuery(query);
            rs = st.executeQuery(query);
            pcklasse PCKlasse;
            
            while(rs.next())
            {
                PCKlasse = new pcklasse(rs.getInt("PCKlassenID"), rs.getString("Hersteller"), rs.getString("Modell"));
                pcList.add(PCKlasse);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return pcList;
    }  
    


    private void executeSQLQuery(String query, String message)
    {
        Connection conn = DBConnection.getConnection2();
        Statement st;
        try
        {
            st = conn.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                 
            //    DefaultTableModel model = (DefaultTableModel)jTable_Display_Pcs.getModel();
            //    model.setRowCount(0);
            //    Show_Pcs_In_JTable();
                
                JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
            } else{
                JOptionPane.showMessageDialog(null, "Data Not "+message);    
            }
        }catch(Exception ex) 
        {
            
        }
        
    }




    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menueaufruf = new javax.swing.JButton();
        PCKlappliste = new javax.swing.JComboBox<>();
        EingabeAnzahl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DruckenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menueaufruf.setText("Menü");
        menueaufruf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueaufrufActionPerformed(evt);
            }
        });

        EingabeAnzahl.setText("zahl");
        EingabeAnzahl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EingabeAnzahlActionPerformed(evt);
            }
        });

        jLabel1.setText("Anzahl");

        DruckenButton.setText("Drucken");
        DruckenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DruckenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PCKlappliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EingabeAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(menueaufruf))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DruckenButton)
                        .addGap(157, 157, 157)))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCKlappliste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EingabeAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(DruckenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(menueaufruf)
                .addGap(243, 243, 243))
        );

        menueaufruf.getAccessibleContext().setAccessibleName("menueaufruf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menueaufrufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueaufrufActionPerformed
// TODO add your handling code here:
        this.dispose();
        menue mm = new menue();
        mm.setVisible(true);
//        mm.show();        

    }//GEN-LAST:event_menueaufrufActionPerformed

    private void DruckenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DruckenButtonActionPerformed
 
        int cbm = PCKlappliste.getSelectedIndex();
        String cbmInhalt = PCKlappliste.getItemAt(cbm);
//        System.out.println(PCKlassenIDsListe.get(cbm) + "001");
        
 //       drucken.druckStart(PCKlassenIDsListe.get(cbm) + "001");
//        drucken.druckStart(cbmInhalt);
        System.out.println(EingabeAnzahl.getText());
        
        //  noch zu machen:
        // überprüfung, führende Leerzeichen weg etc.
        //  java.lang.NumberFormatException abfangen bei falscher Eingabe!!
        int ZahlderLabel = Integer.parseInt(EingabeAnzahl.getText());

        String EinzelQuery = " INSERT INTO PC_Bestand (PCKlassenID) VALUE (" + PCKlassenIDsListe.get(cbm) + ");";
        String MehrfachQuery = " ";
        for (int i = 0; i < ZahlderLabel; i++) {
            MehrfachQuery += EinzelQuery;
        }
        System.out.println(MehrfachQuery);
        executeSQLQuery(MehrfachQuery, "Inserted");       

    }//GEN-LAST:event_DruckenButtonActionPerformed

    private void EingabeAnzahlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EingabeAnzahlActionPerformed
        // TODO add your handling code here:
        System.out.println("oops");
    }//GEN-LAST:event_EingabeAnzahlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuchungRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuchungRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuchungRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuchungRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuchungRechner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DruckenButton;
    private javax.swing.JTextField EingabeAnzahl;
    private javax.swing.JComboBox<String> PCKlappliste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menueaufruf;
    // End of variables declaration//GEN-END:variables
}
