/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wws;

/**
 *
 * @author bfw
 */
public class menue extends javax.swing.JFrame {

    /**
     * Creates new form menue
     */
    public menue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menue_etikettendruck = new javax.swing.JButton();
    menue_rechnerverwaltung = new javax.swing.JButton();
    menue_geratepruppenverwaltung = new javax.swing.JButton();
    menue_geratepruppenverwaltung1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    menue_etikettendruck.setText("Hardwaregruppen - Ein-/Ausgang");
    menue_etikettendruck.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menue_etikettendruckActionPerformed(evt);
      }
    });

    menue_rechnerverwaltung.setText("Einzelrechner verwalten");
    menue_rechnerverwaltung.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menue_rechnerverwaltungActionPerformed(evt);
      }
    });

    menue_geratepruppenverwaltung.setText("Bestand anzeigen");
    menue_geratepruppenverwaltung.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menue_geratepruppenverwaltungActionPerformed(evt);
      }
    });

    menue_geratepruppenverwaltung1.setText("Hardwaregruppen");
    menue_geratepruppenverwaltung1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menue_geratepruppenverwaltung1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(101, 101, 101)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(menue_geratepruppenverwaltung, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(menue_geratepruppenverwaltung1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(menue_etikettendruck, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
        .addComponent(menue_rechnerverwaltung, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(100, 100, 100))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(88, 88, 88)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(menue_etikettendruck, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(menue_rechnerverwaltung, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(74, 74, 74)
        .addComponent(menue_geratepruppenverwaltung, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
        .addComponent(menue_geratepruppenverwaltung1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(120, 120, 120))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void menue_etikettendruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menue_etikettendruckActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Bestandsverwaltung mm = new Bestandsverwaltung();
        mm.show();
        
    }//GEN-LAST:event_menue_etikettendruckActionPerformed

    private void menue_rechnerverwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menue_rechnerverwaltungActionPerformed

        this.dispose();
        NewJFrame mm = new NewJFrame();
        mm.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_menue_rechnerverwaltungActionPerformed

  private void menue_geratepruppenverwaltungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menue_geratepruppenverwaltungActionPerformed
                    this.dispose();
                    Gruppenverwaltung mm = new Gruppenverwaltung();
                    mm.show();
// TODO add your handling code here:
  }//GEN-LAST:event_menue_geratepruppenverwaltungActionPerformed

  private void menue_geratepruppenverwaltung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menue_geratepruppenverwaltung1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_menue_geratepruppenverwaltung1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menue().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton menue_etikettendruck;
  private javax.swing.JButton menue_geratepruppenverwaltung;
  private javax.swing.JButton menue_geratepruppenverwaltung1;
  private javax.swing.JButton menue_rechnerverwaltung;
  // End of variables declaration//GEN-END:variables
}
