/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wws;

import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author bfw
 */
public class NeueVerbindungJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NeueVerbindungJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextName = new javax.swing.JTextField();
        jTextUrl = new javax.swing.JTextField();
        jTextBenutzer = new javax.swing.JTextField();
        jTextPasswort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonEingabe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextDB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("URL");

        jLabel3.setText("Benutzer");

        jLabel4.setText("Passwort");

        jButtonEingabe.setText("Eingabe");
        jButtonEingabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEingabeActionPerformed(evt);
            }
        });

        jLabel5.setText("Datenbank");

        jTextDB.setText("Projekt_WWS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButtonEingabe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextName)
                    .addComponent(jTextUrl)
                    .addComponent(jTextBenutzer)
                    .addComponent(jTextPasswort, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jTextDB))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextBenutzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPasswort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonEingabe)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEingabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEingabeActionPerformed
        // TODO add your handling code here:
        String tName = jTextName.getText();
        String tUrl = jTextUrl.getText();
        String tDB = jTextDB.getText();
        String tBenutzer = jTextBenutzer.getText();
        String tPasswort = jTextPasswort.getText();
        
        String regex1 = "((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\\.){3}"
                    +"(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])";
        String regex2 = "[a-zA-Z0-9-]+\\.[a-zA-Z0-9]+(/[a-zA-Z0-9-]+)*";
        String regex3 = "localhost";
        String regexDB = "[a-zA-Z0-9_-]+";
        
        if (tName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "bitte Name eingeben"); 
        } else if (tUrl.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "bitte URL eingeben");                         
        } else if (!(tUrl.matches(regex1)||tUrl.matches(regex2)||tUrl.matches(regex3))) {
                        JOptionPane.showMessageDialog(null, "URL nicht ok");                                         
        } else if (tDB.isEmpty()) {
                                JOptionPane.showMessageDialog(null, "bitte DB Name eingeben");
        } else if (!tDB.matches(regexDB)) {
                                JOptionPane.showMessageDialog(null, "DB Name nicht ok");
        } else if (tBenutzer.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "bitte Benutzer eingeben"); 
        } else if (tPasswort.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "bitte Passwort eingeben"); 
        } else   {
            String regex5 = "^/";
            String regex6 = "/$";  
//            if 
            VerbindungXML.setVerbindung(tName, "jdbc:mysql://"+tUrl+"/"+tDB, tBenutzer, tPasswort);
           
            this.dispose();            
        }

    }//GEN-LAST:event_jButtonEingabeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NeueVerbindungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NeueVerbindungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NeueVerbindungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NeueVerbindungJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NeueVerbindungJDialog dialog = new NeueVerbindungJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEingabe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextBenutzer;
    private javax.swing.JTextField jTextDB;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPasswort;
    private javax.swing.JTextField jTextUrl;
    // End of variables declaration//GEN-END:variables
}
