
package wws;

//import com.mysql.jdbc.Connection;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

//import java.sql.*;


public class NewJFrame extends javax.swing.JFrame {

    /*
    static NewJFrame run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
*/
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        Show_Pcs_In_JTable();
    }

    /*
    public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://192.168.151.123/Projekt_WWS", "IT1601", "IT1601");
            //con = DriverManager.getConnection("jdbc:mysql://localhost:3306/projekt_wws", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    */
    
    public ArrayList<pc> getPcList()
    {
        ArrayList<pc> pcList = new ArrayList<pc>();
    //    Connection connection = getConnection();
        Connection connection = DBConnection.getConnection2();
        
        
        String query = "SELECT * FROM `pcs` ";
        Statement st;
        ResultSet rs;
        
        try
        {
            st = connection.createStatement();
            //rs = st.executeQuery(query);
            rs = st.executeQuery(query);
            pc PC;
            
            while(rs.next())
            {
                PC = new pc(rs.getInt("wws_barcode"), rs.getInt("bfw_barcode"), rs.getString("hersteller"), rs.getString("modell"));
                pcList.add(PC);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return pcList;
    }
    
    // Zeigt Daten in Tabelle an
    
    public void Show_Pcs_In_JTable()
    {
        ArrayList<pc> list = getPcList();
        
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Pcs.getModel();
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getWWS_Barcode();
            row[1] = list.get(i).getBFW_Barcode();
            row[2] = list.get(i).getHersteller();
            row[3] = list.get(i).getModell();
            
            model.addRow(row);
        }
    }
    
    //Zegit markierte Zeile in Eingabefeld
    
    public void executeSQLQuery(String query, String message)
    {
        Connection conn = DBConnection.getConnection2();
        Statement st;
        try
        {
            st = conn.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                // refresh jtable data
                
                DefaultTableModel model = (DefaultTableModel)jTable_Display_Pcs.getModel();
                model.setRowCount(0);
                Show_Pcs_In_JTable();
                
                JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
            } else{
                JOptionPane.showMessageDialog(null, "Data Not "+message);    
            }
        }catch(Exception ex) 
        {
            
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jTextField_wwsbarcode = new javax.swing.JTextField();
    jTextField_bfwbarcode = new javax.swing.JTextField();
    jTextField_hersteller = new javax.swing.JTextField();
    jTextField_modell = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable_Display_Pcs = new javax.swing.JTable();
    jButton_insert = new javax.swing.JButton();
    jButton_update = new javax.swing.JButton();
    jButton_delete = new javax.swing.JButton();
    menueaufruf = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jLabel1.setText("WWS_Barcode");

    jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jLabel2.setText("Modell");

    jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jLabel3.setText("BFW_Barcode");

    jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jLabel4.setText("Hersteller");

    jTextField_wwsbarcode.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

    jTextField_bfwbarcode.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jTextField_bfwbarcode.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField_bfwbarcodeActionPerformed(evt);
      }
    });

    jTextField_hersteller.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

    jTextField_modell.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

    jTable_Display_Pcs.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "WWS_Barcode", "BFW_Barcode", "Hersteller", "Modell"
      }
    ));
    jTable_Display_Pcs.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable_Display_PcsMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jTable_Display_Pcs);

    jButton_insert.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jButton_insert.setText("Insert");
    jButton_insert.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_insertActionPerformed(evt);
      }
    });

    jButton_update.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jButton_update.setText("Update");
    jButton_update.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_updateActionPerformed(evt);
      }
    });

    jButton_delete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
    jButton_delete.setText("Delete");
    jButton_delete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_deleteActionPerformed(evt);
      }
    });

    menueaufruf.setText("Menü");
    menueaufruf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menueaufrufActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(65, 65, 65)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField_wwsbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_bfwbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_hersteller, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_modell, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(menueaufruf, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton_delete)
            .addGap(74, 74, 74)))
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGap(90, 90, 90)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTextField_wwsbarcode)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_bfwbarcode))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_hersteller))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField_modell))
            .addGap(79, 79, 79)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(102, 102, 102))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(4, 4, 4)
        .addComponent(menueaufruf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(99, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jTextField_bfwbarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bfwbarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bfwbarcodeActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        
        String query = "INSERT INTO `pcs`(`wws_barcode`,`bfw_barcode`, `hersteller`, `modell`) VALUES ('"+jTextField_wwsbarcode.getText()+"','"+jTextField_bfwbarcode.getText()+"','"+jTextField_hersteller.getText()+"','"+jTextField_modell.getText()+"')";
        
        executeSQLQuery(query, "Inserted");
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        
        String query = "UPDATE `pcs` SET `bfw_barcode`='"+jTextField_bfwbarcode.getText()+"',`hersteller`='"+jTextField_hersteller.getText()+"',`modell`='"+jTextField_modell.getText()+"' WHERE wws_barcode="+jTextField_wwsbarcode.getText();
        
        executeSQLQuery(query, "Updated");
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        
        String query = "DELETE FROM `pcs` WHERE wws_barcode = "+jTextField_wwsbarcode.getText();
        
        executeSQLQuery(query, "Deleted");
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jTable_Display_PcsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_PcsMouseClicked
        // Zeigt ausgwählte Zeile in Eingabefeldern
        int i = jTable_Display_Pcs.getSelectedRow();
        TableModel model = jTable_Display_Pcs.getModel();
        jTextField_wwsbarcode.setText(model.getValueAt(i,0).toString());
        jTextField_bfwbarcode.setText(model.getValueAt(i,1).toString());
        jTextField_hersteller.setText(model.getValueAt(i,2).toString());
        jTextField_modell.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable_Display_PcsMouseClicked

    private void menueaufrufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueaufrufActionPerformed

        this.dispose();
        menue mm = new menue();
        mm.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_menueaufrufActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_delete;
  private javax.swing.JButton jButton_insert;
  private javax.swing.JButton jButton_update;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable_Display_Pcs;
  private javax.swing.JTextField jTextField_bfwbarcode;
  private javax.swing.JTextField jTextField_hersteller;
  private javax.swing.JTextField jTextField_modell;
  private javax.swing.JTextField jTextField_wwsbarcode;
  private javax.swing.JButton menueaufruf;
  // End of variables declaration//GEN-END:variables

    private Object DBConnection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
